[build-system]
requires = ["hatchling>=1.20.0"]
build-backend = "hatchling.build"

[project]
name = "lib"
version = "2.0.8"
description = ""
requires-python = ">=3.8,<4.0"

classifiers = [
]

dependencies = [
    'sphinx==7.3.7'
]

[tool.hatch.build.targets.wheel]
packages = ["lib"]
