name: release

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          repository: qbittorrent/qBittorrent

      - run: git clone --depth=1 --recurse-submodules --branch v2.0.10 https://github.com/arvidn/libtorrent.git libtorrent

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential pkg-config automake libtool git \
              zlib1g-dev libssl-dev libgeoip-dev \
              libboost-dev libboost-system-dev \
              libboost-chrono-dev libboost-random-dev cmake ninja-build

      - run: apt update
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          archives: icu qtbase qtdeclarative qtsvg qttools
          cache: true

      - run: |
          cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug
          cmake --build build
          sudo cmake --install build
        working-directory: libtorrent

      - run: cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Debug -D TESTING=OFF -D QT6=ON -D GUI=OFF
      - run: cmake --build build
