name: release

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - run: git clone --depth=1 https://github.com/qbittorrent/qBittorrent
      - run: git clone --depth=1 --recurse-submodules --branch v2.0.10 https://github.com/qbittorrent/qBittorrent libtorrent

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential pkg-config automake libtool git zlib1g-dev libssl-dev libgeoip-dev
          sudo apt-get install -y libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev
          sudo apt-get install -y cmake ninja-build
          sudo apt install qt6-base-dev qt6-base-private-dev qt6-tools-dev

      - run: cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D deprecated-functions=OFF
        working-directory: libtorrent

      - run: cmake -B build build
        working-directory: libtorrent

      - run: sudo cmake --install build
        working-directory: libtorrent

      - run: cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo -D CMAKE_CXX_FLAGS=-Werror -Wno-error=deprecated-declarations -D TESTING=OFF -D QT6=ON -D GUI=OFF
      - run: cmake -B build build
