name: release

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          repository: qbittorrent/qBittorrent

      - run: git clone --depth=1 --recurse-submodules --branch v2.0.10 https://github.com/arvidn/libtorrent.git libtorrent

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.*'
          archives: icu qtbase qtdeclarative qtsvg qttools
          cache: true

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - run: >-
          sudo apt-get install -y
          build-essential pkg-config automake libtool git zlib1g-dev
          libssl-dev libgeoip-dev libboost-dev libboost-system-dev
          libboost-chrono-dev libboost-random-dev cmake ninja-build

      - run: |
          cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=RelWithDebInfo \
              -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build build
          sudo cmake --install build
        working-directory: libtorrent

      - run: |
          cmake -B build -G Ninja -D BUILD_SHARED_LIBS=OFF \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D TESTING=OFF -D QT6=ON -D GUI=OFF \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache
      - run: cmake --build build


      - uses: actions/upload-artifact@v4
        with:
          path: build
