name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Previous Tag
        id: tag
        uses: trim21/changelog-previous-tag@master
        with:
          token: ${{ github.token }}

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ steps.tag.outputs.previousTag }}
          writeToFile: false

      - name: Upload Github Release
        run: gh release create "${GITHUB_REF}" --notes "${CHANGELOG}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: "${{ steps.changelog.outputs.changes }}"
