name: release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: seasonalmatcha/conventional-commit-changelog@latest
        id: changelog
        with:
          to: ${{ github.ref }}

      - name: Upload Github Release
        run: gh release create "${GITHUB_REF}" --notes-file "${{steps.build_changelog.outputs.changelog}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
